\set ON_ERROR_STOP on
BEGIN;
\ir migraciones/03_personal_usuario.sql
\ir auth_usuario_datos.sql
\ir funciones/caja/cajas/caj_listar_cajas.sql
\ir funciones/caja/cajas/caj_obtener_caja.sql
\ir funciones/caja/movimientos/caj_listar_movimientos.sql
\ir funciones/caja/turnos/caj_abrir_turno.sql
\ir funciones/caja/turnos/caj_listar_turnos.sql
\ir funciones/caja/turnos/caj_obtener_turno.sql
\ir funciones/caja/turnos/caj_resumen_turno.sql
\ir funciones/cuentas-por-cobrar/cxc_listar_movimientos.sql
\ir funciones/cuentas-por-cobrar/cxc_obtener_movimiento.sql
\ir funciones/cuentas-por-pagar/cxp_obtener_movimiento.sql
\ir funciones/gastos-administrativos/gastos/gad_obtener_gasto.sql
\ir funciones/gastos-diarios/gastos/gdo_obtener_dia.sql
\ir funciones/general/almacenes/gen_listar_almacenes.sql
\ir funciones/general/almacenes/gen_obtener_almacen.sql
\ir funciones/general/estaciones/gen_listar_estaciones.sql
\ir funciones/general/estaciones/gen_obtener_estacion.sql
\ir funciones/general/sucursales/gen_listar_sucursales.sql
\ir funciones/general/sucursales/gen_obtener_sucursal.sql
\ir funciones/login/auth_obtener_usuario_por_login.sql
\ir funciones/pedidos/ven_autorizar_anulacion.sql
\ir funciones/pedidos/ven_listar_pedidos.sql
\ir funciones/pedidos/ven_obtener_pedido.sql
\ir funciones/pedidos/ven_pedido_abrir.sql
\ir funciones/personas/convenios/cli_listar_convenios.sql
\ir funciones/personas/convenios/cli_obtener_convenio.sql
\ir funciones/personas/personas/cli_listar_personas.sql
\ir funciones/personas/personas/cli_obtener_persona.sql
\ir funciones/planilla/pagos/pla_obtener_pago.sql
\ir funciones/planilla/trabajadores/pla_activar_trabajador.sql
\ir funciones/planilla/trabajadores/pla_actualizar_trabajador.sql
\ir funciones/planilla/trabajadores/pla_crear_trabajador.sql
\ir funciones/planilla/trabajadores/pla_eliminar_trabajador.sql
\ir funciones/planilla/trabajadores/pla_listar_trabajadores.sql
\ir funciones/planilla/trabajadores/pla_obtener_trabajador.sql
\ir funciones/productos/categoria-producto/pro_listar_categorias.sql
\ir funciones/productos/categoria-producto/pro_obtener_categoria.sql
\ir funciones/productos/productos/pro_obtener_producto.sql
\ir funciones/productos/sub-categorias/pro_listar_sub_categorias.sql
\ir funciones/productos/sub-categorias/pro_obtener_sub_categoria.sql
\ir funciones/roles/auth_asignar_roles_usuario.sql
\ir funciones/sesiones/auth_crear_sesion.sql
\ir funciones/sesiones/auth_obtener_sesion.sql
\ir funciones/sesiones/auth_validar_sesion.sql
\ir funciones/usuarios/auth_activar_usuario.sql
\ir funciones/usuarios/auth_actualizar_usuario.sql
\ir funciones/usuarios/auth_crear_usuario.sql
\ir funciones/usuarios/auth_eliminar_usuario.sql
\ir funciones/usuarios/auth_listar_usuarios.sql
\ir funciones/usuarios/auth_listar_trabajadores_disponibles.sql
\ir funciones/usuarios/auth_obtener_usuario.sql
COMMIT;
