-- Solo estructura. No copia ni elimina datos del catálogo genérico.
CREATE TABLE IF NOT EXISTS pro_tipo_producto (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL CHECK (length(trim(nombre)) > 0),
  permite_venta BOOLEAN NOT NULL DEFAULT FALSE,
  requiere_receta BOOLEAN NOT NULL DEFAULT FALSE,
  requiere_estacion BOOLEAN NOT NULL DEFAULT FALSE,
  permite_stock_inicial BOOLEAN NOT NULL DEFAULT TRUE,
  estado SMALLINT NOT NULL DEFAULT 1 CHECK (estado IN (0, 1)),
  id_usuario_creacion BIGINT,
  id_usuario_modificacion BIGINT,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pro_tipo_producto_nombre ON pro_tipo_producto (lower(trim(nombre)));
-- NOT VALID permite cargar manualmente los tipos históricos antes de validar.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pro_producto_tipo' AND conrelid = 'pro_producto'::regclass) THEN
    ALTER TABLE pro_producto ADD CONSTRAINT fk_pro_producto_tipo
      FOREIGN KEY (tipo_producto) REFERENCES pro_tipo_producto(id) NOT VALID;
  END IF;
END $$;
